# .travis.yml 文件

# 声明构建语言环境
language: android
jdk: oraclejdk8 #lamda
sudo: false

notifications:
  email:
    recipients:
    - senrsl@aol.com
    on_success: change
    on_failure: always

env:
  global:
  - ANDROID_API_LEVEL=27
  - ANDROID_EMULATOR_LEVEL=19
  - ANDROID_BUILD_TOOLS_VERSION=27.0.3
  - ADB_INSTALL_TIMEOUT=20
  - ANDROID_ABI=armeabi-v7a
  - ANDROID_TAG=google_apis
  - QEMU_AUDIO_DRV=none

android:        # 配置信息
  components:
  - tools # to get the new `repository-11.xml`
  - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
  - platform-tools
  # 你可能需要修改下面两项的版本
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - android-$ANDROID_EMULATOR_LEVEL
  # Android Support Repository
  - extra-android-m2repository
  - extra-google-m2repository
  # Support Library
  - extra-android-support
  # 镜像
  - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMULATOR_LEVEL

licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

before_install:
  - yes | sdkmanager "platforms;android-27"

before_script:
# Create and start emulator 已废弃
  - android list targets
  - adb devices
#  - echo no | android create avd --force -n test -t "android-"$ANDROID_EMULATOR_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
#  - emulator -avd test -no-window &
#  - android-wait-for-emulator

script:
  - echo "Travis 分支 is $TRAVIS_BRANCH"
#  - ./gradlew test                     # unit
#  - ./gradlew app:connectedAndroidTest # espresso
#  - ./gradlew assembleRelease    #这个是打release包
  - ./gradlew installDebug    #这个是打debug包安装

after_failure:
  - cat $TRAVIS_BUILD_DIR/dog/build/reports/androidTests/connected/index.html
  - cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml

## 部署
#deploy:
#  # 部署到GitHub Release。
#  # 除此之外，Travis CI还支持发布到fir.im、AWS、Google App Engine等
#  provider: releases
#  # Github oauth token
#  api_key: "GITHUB OAUTH TOKEN"
#  # 部署文件路径；对于Android就部署生成的 apk 文件
#  file: "FILE TO UPLOAD"
#  # 避免 Travis CI在部署之前清空生成的APK文件
#  skip_cleanup: true
#  # 发布时机
#  on:
#    # tags设置为true表示只有在有tag的情况下才部署
#    tags: true